name: "VPN.FAIL"

on:
  workflow_dispatch:
  schedule:
    - cron: '30 */1 * * *'

jobs:
  HiN-VPN:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php index.php
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"
          git config credential.helper store
          git add -A
          git commit -m "🚀 Last Run - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
